import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'data/stock_repository.dart';
import 'models/product.dart';

/// Branch-to-branch stock movement. Refill lines carry a physical cylinder;
/// the destination records its matching empty cylinder when it is returned.
class StockTransfersPage extends StatefulWidget {
  const StockTransfersPage({super.key});
  @override State<StockTransfersPage> createState() => _StockTransfersPageState();
}
class _StockTransfersPageState extends State<StockTransfersPage> {
  final _db=Supabase.instance.client; final _stock=StockRepository();
  List<Map<String,dynamic>> _rows=[]; bool _loading=true; String? _error;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { setState(()=>_loading=true); try { final data=await _db.from('stock_transfers').select('*, source:branches!stock_transfers_source_branch_id_fkey(name), destination:branches!stock_transfers_destination_branch_id_fkey(name), stock_transfer_items(*, product:products(name,product_type))').order('created_at',ascending:false); if(mounted)setState(()=>_rows=List<Map<String,dynamic>>.from(data)); } catch(e){_error='$e';} if(mounted)setState(()=>_loading=false); }
  Future<void> _call(String fn, Map<String,dynamic> params) async { try{await _db.rpc(fn,params:params);await _load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Transfer updated.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
  Future<void> _create() async { final branches=await _stock.fetchBranches(); final products=List<Map<String,dynamic>>.from(await _db.from('products').select('id,name,product_type').eq('is_active',true).neq('product_type','service').order('name')); if(!mounted)return; String? from,to,pid; final qty=TextEditingController(text:'1'); await showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(_,setModal)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,20+MediaQuery.of(ctx).viewInsets.bottom),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('New stock transfer',style:Theme.of(ctx).textTheme.titleLarge),const SizedBox(height:8),const Text('Refills remain linked to their matching cylinder until the destination marks the empty cylinder returned.'),DropdownButtonFormField<String>(value:from,decoration:const InputDecoration(labelText:'From branch'),items:[for(final b in branches)DropdownMenuItem(value:b['id'] as String,child:Text(b['name'] as String))],onChanged:(v)=>setModal(()=>from=v)),DropdownButtonFormField<String>(value:to,decoration:const InputDecoration(labelText:'To branch'),items:[for(final b in branches.where((b)=>b['id']!=from))DropdownMenuItem(value:b['id'] as String,child:Text(b['name'] as String))],onChanged:(v)=>setModal(()=>to=v)),DropdownButtonFormField<String>(value:pid,decoration:const InputDecoration(labelText:'Product'),items:[for(final p in products)DropdownMenuItem(value:p['id'] as String,child:Text('${p['name']} · ${p['product_type']}'))],onChanged:(v)=>setModal(()=>pid=v)),TextField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity')),const SizedBox(height:14),Align(alignment:Alignment.centerRight,child:FilledButton(onPressed:()async{final q=int.tryParse(qty.text)??0;if(from==null||to==null||pid==null||q<1)return;try{final transfer=await _db.from('stock_transfers').insert({'source_branch_id':from,'destination_branch_id':to}).select('id').single();await _db.from('stock_transfer_items').insert({'transfer_id':transfer['id'],'product_id':pid,'quantity':q});if(ctx.mounted)Navigator.pop(ctx);await _load();}catch(e){if(ctx.mounted)ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text('$e')));}},child:const Text('Save draft')))])))); qty.dispose(); }
  @override Widget build(BuildContext context)=>Scaffold(floatingActionButton:FloatingActionButton.extended(onPressed:_create,icon:const Icon(Icons.swap_horiz),label:const Text('New transfer')),body:_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Text(_error!)):_rows.isEmpty?const Center(child:Text('No stock transfers yet.')):RefreshIndicator(onRefresh:_load,child:ListView.builder(padding:const EdgeInsets.all(12),itemCount:_rows.length,itemBuilder:(_,i)=>_card(_rows[i])));
  Widget _card(Map<String,dynamic> r){final status=r['status'] as String;final items=List<Map<String,dynamic>>.from(r['stock_transfer_items']??[]);return Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r['transfer_no']??'Transfer',style:Theme.of(context).textTheme.titleMedium)),Chip(label:Text(status.toUpperCase()))]),Text('${(r['source'] as Map?)?['name']??''} → ${(r['destination'] as Map?)?['name']??''}'),const SizedBox(height:7),for(final i in items)_line(i,status),if(status=='draft')Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:()=>_call('dispatch_stock_transfer',{'p_transfer_id':r['id']}),icon:const Icon(Icons.local_shipping_outlined),label:const Text('Dispatch'))),if(status=='dispatched')Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:()=>_call('receive_stock_transfer',{'p_transfer_id':r['id']}),icon:const Icon(Icons.inventory_outlined),label:const Text('Confirm receipt')))])));}
  Widget _line(Map<String,dynamic> i,String status){final p=Map<String,dynamic>.from(i['product']??{});final q=i['quantity'] as int;final done=i['cylinders_returned'] as int? ?? 0;final refill=p['product_type']=='refill';return Row(children:[Expanded(child:Text('${p['name']} × $q${refill?' · cylinder returned $done/$q':''}')),if(refill&&(status=='received'||status=='returned')&&done<q)TextButton(onPressed:()=>_call('return_transfer_cylinders',{'p_transfer_item_id':i['id'],'p_quantity':q-done}),child:const Text('Mark returned'))]);}
}
